In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
#Concatenation of Numpy arrays
A1 = np.arange(25).reshape(5,5)
B1 = np.random.randn(25).reshape(5,5)
print(A1)
print(B1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[-0.11541322  1.93174639 -1.46867815  0.14091262 -1.03039687]
 [-0.29951717 -0.06711707  1.09493619 -0.89382752  0.50939873]
 [ 0.4147568   1.51391426  0.77600308  0.09857495  1.63587227]
 [ 1.30510559 -0.00204826  0.46952267  0.62317868 -0.32998791]
 [-1.05391556 -0.76140403  1.03771397 -0.47649002  1.47746562]]


In [16]:
np.concatenate([A1,B1],axis=1)

array([[ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  4.00000000e+00, -1.15413221e-01,
         1.93174639e+00, -1.46867815e+00,  1.40912623e-01,
        -1.03039687e+00],
       [ 5.00000000e+00,  6.00000000e+00,  7.00000000e+00,
         8.00000000e+00,  9.00000000e+00, -2.99517173e-01,
        -6.71170685e-02,  1.09493619e+00, -8.93827525e-01,
         5.09398734e-01],
       [ 1.00000000e+01,  1.10000000e+01,  1.20000000e+01,
         1.30000000e+01,  1.40000000e+01,  4.14756798e-01,
         1.51391426e+00,  7.76003082e-01,  9.85749540e-02,
         1.63587227e+00],
       [ 1.50000000e+01,  1.60000000e+01,  1.70000000e+01,
         1.80000000e+01,  1.90000000e+01,  1.30510559e+00,
        -2.04826052e-03,  4.69522667e-01,  6.23178675e-01,
        -3.29987910e-01],
       [ 2.00000000e+01,  2.10000000e+01,  2.20000000e+01,
         2.30000000e+01,  2.40000000e+01, -1.05391556e+00,
        -7.61404025e-01,  1.03771397e+00, -4.76490022e-01,
         1.

In [7]:
np.concatenate([A1,B1])

array([[ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  4.00000000e+00],
       [ 5.00000000e+00,  6.00000000e+00,  7.00000000e+00,
         8.00000000e+00,  9.00000000e+00],
       [ 1.00000000e+01,  1.10000000e+01,  1.20000000e+01,
         1.30000000e+01,  1.40000000e+01],
       [ 1.50000000e+01,  1.60000000e+01,  1.70000000e+01,
         1.80000000e+01,  1.90000000e+01],
       [ 2.00000000e+01,  2.10000000e+01,  2.20000000e+01,
         2.30000000e+01,  2.40000000e+01],
       [-1.15413221e-01,  1.93174639e+00, -1.46867815e+00,
         1.40912623e-01, -1.03039687e+00],
       [-2.99517173e-01, -6.71170685e-02,  1.09493619e+00,
        -8.93827525e-01,  5.09398734e-01],
       [ 4.14756798e-01,  1.51391426e+00,  7.76003082e-01,
         9.85749540e-02,  1.63587227e+00],
       [ 1.30510559e+00, -2.04826052e-03,  4.69522667e-01,
         6.23178675e-01, -3.29987910e-01],
       [-1.05391556e+00, -7.61404025e-01,  1.03771397e+00,
        -4.76490022e-01

In [8]:
#Concatenation of Pandas Series
s1 = Series([100,200,300], index=list('ABC'))
s2 = Series([400,500], index=list('DE'))
print(s1)
print(s2)

A    100
B    200
C    300
dtype: int64
D    400
E    500
dtype: int64


In [12]:
pd.concat([s1,s2], axis=1)

0      1
A  100.0    NaN
B  200.0    NaN
C  300.0    NaN
D    NaN  400.0
E    NaN  500.0

In [13]:
#Concatenation in Pandas DataFrame
df1 = DataFrame(np.random.randn(12).reshape(4,3),columns=list('ABC'))
df2 = DataFrame(np.arange(9).reshape(3,3),columns=list('ABD'))
print(df1)
print(df2)

          A         B         C
0  0.660183  0.510650 -0.247445
1 -0.285600 -0.368194 -0.004347
2 -0.546191 -1.016405 -0.344565
3  0.912491 -0.662765  1.215090
   A  B  D
0  0  1  2
1  3  4  5
2  6  7  8


In [14]:
pd.concat([df1,df2])

A         B         C    D
0  0.660183  0.510650 -0.247445  NaN
1 -0.285600 -0.368194 -0.004347  NaN
2 -0.546191 -1.016405 -0.344565  NaN
3  0.912491 -0.662765  1.215090  NaN
0  0.000000  1.000000       NaN  2.0
1  3.000000  4.000000       NaN  5.0
2  6.000000  7.000000       NaN  8.0

In [17]:
pd.concat([df1,df2], ignore_index=True)

A         B         C    D
0  0.660183  0.510650 -0.247445  NaN
1 -0.285600 -0.368194 -0.004347  NaN
2 -0.546191 -1.016405 -0.344565  NaN
3  0.912491 -0.662765  1.215090  NaN
4  0.000000  1.000000       NaN  2.0
5  3.000000  4.000000       NaN  5.0
6  6.000000  7.000000       NaN  8.0