In [1]:
import numpy as np

In [2]:
!pip install pandas

In [5]:
#What is pandas
#What is series
import pandas as pd
from pandas import Series

In [6]:
#Create a simple series variable
s1 = Series([5,10,15,20])
print(s1)

0     5
1    10
2    15
3    20
dtype: int64


In [9]:
print(s1.values)

[ 5 10 15 20]


In [11]:
print(s1.index.values)

[0 1 2 3]


In [12]:
#Create a series from numpy
revenue_array = np.array([400,300,200,100])
print(revenue_array)

[400 300 200 100]


In [13]:
revenue_series = Series(revenue_array)
print(revenue_series)

0    400
1    300
2    200
3    100
dtype: int64


In [16]:
#Create series with custom indexes
revenue = Series(revenue_array, index=['uber','ola','jumia','bolt'])
print(revenue)

uber     400
ola      300
jumia    200
bolt     100
dtype: int64


In [17]:
revenue['ola']

300

In [18]:
#Filter a Series based on condition
print(revenue[revenue>250])

uber    400
ola     300
dtype: int64


In [19]:
#Check whether an element is a series
print('ola' in revenue)

True


In [20]:
print('watu' in revenue)

False


In [22]:
#To_dict function
revenue_dict = revenue.to_dict()
print(revenue_dict)

{'uber': 400, 'ola': 300, 'jumia': 200, 'bolt': 100}


In [23]:
#Addition of two series
print(revenue)
print(revenue + revenue)

uber     400
ola      300
jumia    200
bolt     100
dtype: int64
uber     800
ola      600
jumia    400
bolt     200
dtype: int64


In [24]:
#Assign names in a series
revenue.name = "Company - Revenue"
revenue.index.name = "Company Name"
print(revenue)

Company Name
uber     400
ola      300
jumia    200
bolt     100
Name: Company - Revenue, dtype: int64
