In [1]:
import numpy as np

In [2]:
x = np.array([100,400,-50,-40]) #Each element of a
y = np.array([10,15,20,25]) #Each element b
condition = np.array([True,True,False,False]) #Each element cond

z = [a if cond else b for a, cond, b in zip(x, condition ,y)]
print(z)

[100, 400, 20, 25]


In [3]:
#Using numpy.where(conditions, values for true,value for false)

z2 = np.where(condition,x,y)
print(z2)


[100 400  20  25]


In [4]:
z3 = np.where(x>0,1,x)
print(z3)

[  1   1 -50 -40]


In [6]:
#Standard functions of numpy - sum, sum(0), variance , mean(), std()
print(x.sum())

410


In [7]:
 x2 = np.array([[1,2],[3,4]])

In [8]:
print(x2)

[[1 2]
 [3 4]]


In [9]:
print(x2.sum(0))

[4 6]


In [10]:
print(x.mean())


102.5


In [11]:
print(x.std())
print(x.var())

181.71062159378576
33018.75


In [12]:
#Logical AND OR operations - any(), all()
condition2 = np.array([True,False,True])
#OR
print(condition2.any())

#AND
print(condition2.all())

True
False


In [13]:
#Sort() function
unsorted = np.array([1,2,10,6,4,3])
unsorted.sort()
print(unsorted)

[ 1  2  3  4  6 10]


In [14]:
#Unique
arr2 = np.array(['liquid', 'liquid', 'liquid', 'gas', 'gas', 'solid', 'solid'])
print(np.unique(arr2)) 

['gas' 'liquid' 'solid']


In [15]:
#in1d function - used to check whether a list of elements is present in an array or not
print(np.in1d(['solid', 'liquid', 'plasma'],arr2))


[ True  True False]
