In [4]:
import numpy as np

In [13]:
arr = np.arange(10)

In [5]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
#Why do we need to save arrays to the hard drive?


In [8]:
#Saving single array
np.save("saved_array",arr)

In [9]:
#Loading a single array
load_array1 = np.load('saved_array.npy')
print(load_array1)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
#Saving multiple array
arr2 = np.arange(25)
arr3 = np.arange(5)
np.savez('saved_archived.npz', x=arr2, y=arr3)

In [5]:
#loading multiple array
load_npz = np.load('saved_archived.npz')
print(load_npz['x'])
print(load_npz['y'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4]


In [15]:
#Saving array to a text file
np.savetxt('myarray.txt',arr2, delimiter=',')


In [17]:
#Loading array from the text file
load_file = np.loadtxt('myarray.txt', delimiter=',')
print(load_file)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


In [ ]:
#What is a delimeter
