In [1]:
import numpy as np

In [3]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
 #Accessing rows
print(arr2d[0])
print(arr2d[1])

[1 2 3]
[4 5 6]


In [8]:
#Accessing elements of an array
print(arr2d[0][0])

1


In [9]:
print(arr2d[1][2])

6


In [10]:
#Slicing in 2D arrays
slice1 = arr2d[0:1, 0:2]
print(slice1)

[[1 2]]


In [11]:
slice2 = arr2d[0:2,0:3]
print(slice2)

[[1 2 3]
 [4 5 6]]


In [13]:
slicing3 = arr2d[:2, :3]
print(slicing3)

[[1 2 3]
 [4 5 6]]


In [14]:
slice4 = arr2d[1:,2:]

In [15]:
print(slice4)

[[6]
 [9]]


In [17]:
#Using loops to change indexes
#The function shape returns the shape of an array
arr_len = arr2d.shape
print(arr_len)
nrows = arr_len[0]

(3, 3)


In [18]:
for i in range(nrows):
    arr2d[i][0] = i
print(arr2d)    

[[0 2 3]
 [1 5 6]
 [2 8 9]]


In [20]:
#Accessing rows using list of index values
print(arr2d[[0,1]])

[[0 2 3]
 [1 5 6]]


In [21]:
print(arr2d[[1,0]])

[[1 5 6]
 [0 2 3]]
