In [3]:
import numpy as np

In [6]:
#Creating a 1D Numpy Array
mylist1 = [101,102,103]
myArray = np.array(mylist1)
print(myArray)

[101 102 103]


In [8]:
#Creating 2D array from a list
mylist2 = [201,202,203]
myArray2D = np.array([mylist1,mylist2])
print(myArray2D)


[[101 102 103]
 [201 202 203]]


In [9]:
#Tesing on 2D arrays
myArray0D = np.array([mylist1,mylist2])
print(myArray0D)

[[101 102 103]
 [201 202 203]]


In [5]:
#Finding the shape ofArray - Shape
print("myArray Dimensions")
print(myArray.shape)
print("myArray2D Dimensions")
print(myArray2D.shape)

myArray Dimensions
(3,)
myArray2D Dimensions
(2, 3)


In [6]:
#Finding out the dataType of The array
print("myArray DataType")
print(myArray.dtype)
print("myArray2D DataType")
print(myArray2D.dtype)

myArray DataType
int64
myArray2D DataType
int64


In [8]:
#myArray Creation and Initialization Function
zero_array = np.zeros(5)
print(zero_array)

zero_array2 = np.zeros([5,5])
print(zero_array2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#Array Creation and Initialization Functions - Empty
zero_array = np.empty(5)
print(zero_array)

zero_array2 = np.empty([5,5])
print(zero_array2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#Array Creation and Initialization Functions - Eye - Used to create an Identity Matrix
Identity_Array = np.eye(3)
print(Identity_Array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#Array Creation and Initialization Functions - Arange - Arithmetic Progression
AP_array = np.arange(0,50,2)
#AP = Arithmetic Progression
print(AP_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
