In [1]:
!import numpy as np

/bin/bash: import: command not found


In [3]:
import numpy as np

In [4]:
arr = np.arange(100,160,2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [7]:
#Introduction to indexes
#Acces individual elements of arrays
print("First element")
print(arr[0])
print("Second element")
print(arr[1])
print("Third element")
print(arr[2])
print("Fifth element")
print(arr[4])

First element
100
Second element
102
Third element
104
Fifth element
108


In [8]:
#Slicing of Array Indexes arr[start:stop:step]
print(arr[0:5:1])

[100 102 104 106 108]


In [9]:
#updating array using slices
arr[0:5] = 0

In [10]:
print(arr)

[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [11]:
#Interesting point about slicing - Memory allocation - View vs Copy
arr2 = arr[4:10]
print(arr2)

[  0 110 112 114 116 118]


In [5]:
#Copy function() => Creating new numpy memory for array
arr3 = arr.copy()
print(arr3)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [6]:
arr3[:]= 0

In [7]:
print(arr3)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]
