In [1]:
import numpy as np

In [2]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
B = np.arange(5,10)
print(B)

[5 6 7 8 9]


In [4]:
C = np.arange(5,10,2)

In [5]:
print(C)

[5 7 9]


In [7]:
#Function of Numpy arrays - sqrt()
D = np.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [8]:
#Function of Numoy arrays - exp()
E = np.exp(A)
print(E)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [9]:
#Function of Numpy Arrays - random()
F = np.random.randn(5)
print(F)

[-1.264613    0.33842023  0.90626717  0.91750598  0.13351922]


In [10]:
G = np.random.randn(5,5)
print(G)

[[ 0.49296549 -0.35943435  0.7591404   0.26451591  1.87698619]
 [-0.13751774  1.0782197   0.15375461 -0.12211765  1.37953894]
 [-1.1797135   0.74180551  0.67882007 -2.31731742 -0.6420309 ]
 [ 1.01441052  1.38280803  0.16497011 -1.04089073 -0.20534694]
 [ 0.36112598  0.77237579  1.22288316 -0.10166103 -1.38353275]]


In [13]:
#Function of Numpy Arrays - add()
print(A)
print(D)
H = np.add(A,D)
print(H)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]
[ 0.          2.          3.41421356  4.73205081  6.          7.23606798
  8.44948974  9.64575131 10.82842712 12.         13.16227766 14.31662479
 15.46410162 16.60555128 17.74165739]


In [16]:
#Function of Numpy Arrays - maximum
A = np.array([1,5,7,10])
B = np.array([0,6,8,9])
I = np.maximum(A,B)
print(I)

[ 1  6  8 10]


In [ ]:
#Numpy Additional documentation - numpy.org, docs.scipy.org